### ISSUE TITLE
Using existing images

### ISSUE THREAD

**Issue by scherepiuk** [SergeyCherepiuk/fleet#1]
User should be able to specify the name of an existing image and the registry to pull from, as an alternative way to choose the image for the service.

The syntax might look something like this:
```
services:
  cache:
    image: registry/image_name
```
or make the registry an optional property, which is specified separately:
```
services:
  cache:
    registry: registry
    image: image_name
```
